server:
  port: 8500
spring:
  application:
    name: scl-zuul # 服务名称
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@test1:8100/eureka-server1/eureka,http://root:123456@test2:8200/eureka-server2/eureka,http://root:123456@test3:8300/eureka-server3/eureka # 服务注册中心地址
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,routes,hystrix.stream
zuul:
  routes:
    scl-eureka-client-consumer: /secc/**
feign:
  hystrix:
    enabled: true