server:
  port: 8090
spring:
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
feign:
  hystrix:
    enabled: true # 启用Hystrix
ribbon:
  server-list-refresh-interval: 5000 # ribbon每5秒刷新一下server list
management:
  endpoints:
    web:
      exposure:
        include: info,health,hystrix-stream,bus-refresh # actuator暴露端点
  endpoint:
    health:
      show-details: always # 总是展示详细的健康检查信息
