server:
  port: 8600
spring:
  application:
    name: scl-config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TabooNight/Spring-Cloud-Learning
          username: username
          password: password
          search-paths: scl-spring-cloud-config-repo
        health:
          repositories:
            all-health:
              label: master
              name: scl-eureka-client-consumer
              profiles: prod
  security:
    user:
      name: root
      password: 123456
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: bus-refresh
eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://root:123456@test1:8100/eureka-server1/eureka,http://root:123456@test2:8200/eureka-server2/eureka,http://root:123456@test3:8300/eureka-server3/eureka # 服务注册中心地址
