server:
  port: 8600
spring:
  application:
    name: scl-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TabooNight/Spring-Cloud-Learning
          username: username
          password: password
          search-paths: scl-spring-cloud-config-repo
        health:
          repositories:
            all-health:
              label: master
              name: scl-eureka-client-consumer
              profiles: prod
management:
  endpoint:
    health:
      show-details: always
